export const LOGIN_CHECK = 'LOGIN_CHECK';
export const SIGNUP_CHECK = 'SIGNUP_CHECK';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const SIGNOUT_CHECK = 'SIGNOUT_CHECK';